export const ACTION_TYPES = {
  fetchAreas: 'fetchAreas',
  fetchIncidents: 'fetchIncidents',
  fetchInjurySpot: 'fetchInjurySpot',
  fetchInjuryType: 'fetchInjuryType',
  fetchSubAreas: 'fetchSubAreas',
  loginFailure: 'loginFailure',
  loginSuccess: 'loginSuccess',
  logout: 'logout',
  setAdditionalLocationInfo: 'setAdditionalLocationInfo',
  setErrors: 'setErrors',
  setFirstName1: 'setFirstName1',
  setFirstName2: 'setFirstName2',
  setIncident: 'setIncident',
  setIncidentDate: 'setIncidentDate',
  setIncidentDescription: 'setIncidentDescription',
  setIncidentTime: 'setIncidentTime',
  setInjurySpots: 'setInjurySpots',
  setInjuryTypes: 'setInjuryTypes',
  setLastName1: 'setLastName1',
  setLastName2: 'setLastName2',
  setLoad: 'setLoad',
  setMainArea: 'setMainArea',
  setNoWitness: 'setNoWitness',
  setPersonData: 'setPersonData',
  setSubArea: 'setSubArea',
  registerFailure: 'registerFailure',
  registerSuccess: 'registerSuccess',
  resetIncidentData: 'resetIncidentData',
  resetInjuryData: 'resetInjuryData',
  resetPersonalData: 'resetPersonalData',
};

// A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
