export const AT = {
  authError: 'auth_error',
  authRequest: 'auth_request',
  authSuccess: 'auth_success',

  fetchInjurySpots: 'fetch_injury_spots',
  fetchInjuryTypes: 'fetch_injury_types',
  fetchMainAreas: 'fetch_main_areas',
  fetchSubAreas: 'fetch_sub_areas',

  inciError: 'inci_Error',
  inciRequest: 'inci_Request',
  inciSuccess: 'inciSuccess',

  loginFailure: 'loginFailure',
  loginSuccess: 'loginSuccess',
  logout: 'logout',
  setLocationInfo: 'set_location_info',
  setErrors: 'setErrors',
  setFirstName1: 'setFirstName1',
  setFirstName2: 'setFirstName2',
  setIncident: 'setIncident',
  setIncidentDate: 'set_incident_date',
  setIncidentDescription: 'set_incident_description',
  setIncidentTime: 'set_incident_time',
  setInjurySpots: 'set_injury_spots',
  setInjuryTypes: 'set_injury_types',
  setLastName1: 'setLastName1',
  setLastName2: 'setLastName2',
  setLoad: 'setLoad',
  setMainArea: 'set_main_area',
  setNoWitness: 'setNoWitness',
  setPersonData: 'setPersonData',
  setSubArea: 'set_sub_area',
  registerFailure: 'registerFailure',
  registerSuccess: 'registerSuccess',
  resetIncidentData: 'resetIncidentData',
  resetInjuryData: 'resetInjuryData',
  resetPersonalData: 'resetPersonalData',
  resetValidation: 'reset_validation',
};

// A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
