export const ACTION_TYPES = {
  setFirstName1: 'setFirstName1',
  setLastName1: 'setLastName1',
  setFirstName2: 'setFirstName2',
  setLastName2: 'setLastName2',
  setNoWitness: 'setNoWitness',
  setIncidentDate: 'setIncidentDate',
  setIncidentTime: 'setIncidentTime',
  setIncidentDescription: 'setIncidentDescription',
  setMainArea: 'setMainArea',
  setSubArea: 'setSubArea',
  setAdditionalLocationInfo: 'setAdditionalLocationInfo',
  setInjurySpots: 'setInjurySpots',
  setInjuryTypes: 'setInjuryTypes',
  setErrors: 'setErrors',
  setIncErrors: 'setIncErrors',
  setInjErrors: 'setInjErrors',
  fetchAreas: 'fetchAreas',
  fetchSubAreas: 'fetchSubAreas',
  fetchInjurySpot: 'fetchInjurySpot',
  fetchInjuryType: 'fetchInjuryType',
};
